//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BecDevGenEntradaSalidaCprEvent
{
    using System;
    using System.Collections.Generic;
    
    public partial class admCaracteristicasValores
    {
        public int CIDVALORCARACTERISTICA { get; set; }
        public int CIDPADRECARACTERISTICA { get; set; }
        public string CVALORCARACTERISTICA { get; set; }
        public string CNEMOCARACTERISTICA { get; set; }
    }
}
