//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BecDevGenEntradaSalidaCprEvent
{
    using System;
    using System.Collections.Generic;
    
    public partial class admClasificacionesValores
    {
        public int CIDVALORCLASIFICACION { get; set; }
        public string CVALORCLASIFICACION { get; set; }
        public int CIDCLASIFICACION { get; set; }
        public string CCODIGOVALORCLASIFICACION { get; set; }
        public string CSEGCONT1 { get; set; }
        public string CSEGCONT2 { get; set; }
        public string CSEGCONT3 { get; set; }
    }
}
