//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BecDevGenEntradaSalidaCprEvent
{
    using System;
    using System.Collections.Generic;
    
    public partial class admDocumentosModelo
    {
        public int CIDDOCUMENTODE { get; set; }
        public string CDESCRIPCION { get; set; }
        public int CNATURALEZA { get; set; }
        public int CAFECTAEXISTENCIA { get; set; }
        public int CMODULO { get; set; }
        public double CNOFOLIO { get; set; }
        public int CIDCONCEPTODOCTOASUMIDO { get; set; }
        public int CUSACLIENTE { get; set; }
        public int CUSAPROVEEDOR { get; set; }
        public int CIDASIENTOCONTABLE { get; set; }
    }
}
