//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BecDevGenEntradaSalidaCprEvent
{
    using System;
    using System.Collections.Generic;
    
    public partial class admEjercicios
    {
        public int CIDEJERCICIO { get; set; }
        public int CNUMEROEJERCICIO { get; set; }
        public System.DateTime CFECINIPERIODO1 { get; set; }
        public System.DateTime CFECINIPERIODO2 { get; set; }
        public System.DateTime CFECINIPERIODO3 { get; set; }
        public System.DateTime CFECINIPERIODO4 { get; set; }
        public System.DateTime CFECINIPERIODO5 { get; set; }
        public System.DateTime CFECINIPERIODO6 { get; set; }
        public System.DateTime CFECINIPERIODO7 { get; set; }
        public System.DateTime CFECINIPERIODO8 { get; set; }
        public System.DateTime CFECINIPERIODO9 { get; set; }
        public System.DateTime CFECINIPERIODO10 { get; set; }
        public System.DateTime CFECINIPERIODO11 { get; set; }
        public System.DateTime CFECINIPERIODO12 { get; set; }
        public System.DateTime CFECHAFINAL { get; set; }
        public int CEJERCICIO { get; set; }
    }
}
