//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BecDevGenEntradaSalidaCprEvent
{
    using System;
    using System.Collections.Generic;
    
    public partial class admProductosFotos
    {
        public int CIDFOTOPRODUCTO { get; set; }
        public string CNOMBREFOTOPRODUCTO { get; set; }
        public string CFOTOPRODUCTO { get; set; }
    }
}
