//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BecDevGenEntradaSalidaCprEvent
{
    using System;
    using System.Collections.Generic;
    
    public partial class admProductosDetalles
    {
        public int CIDPRODUCTO { get; set; }
        public int CTIPOPRODUCTO { get; set; }
        public int CIDPRODUCTOPADRE { get; set; }
        public int CIDVALORCARACTERISTICA1 { get; set; }
        public int CIDVALORCARACTERISTICA2 { get; set; }
        public int CIDVALORCARACTERISTICA3 { get; set; }
        public string CTIMESTAMP { get; set; }
    }
}
