//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BecDevGenEntradaSalidaCprEvent
{
    using System;
    using System.Collections.Generic;
    
    public partial class admUnidadesMedidaPeso
    {
        public int CIDUNIDAD { get; set; }
        public string CNOMBREUNIDAD { get; set; }
        public string CABREVIATURA { get; set; }
        public string CDESPLIEGUE { get; set; }
        public string CCLAVEINT { get; set; }
        public string CCLAVESAT { get; set; }
    }
}
