//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BecDevGenEntradaSalidaCprEvent
{
    using System;
    using System.Collections.Generic;
    
    public partial class bec_event_documento_abono
    {
        public int id { get; set; }
        public Nullable<int> id_documento_origen { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<double> monto { get; set; }
        public Nullable<int> id_contpaq_documento { get; set; }
        public Nullable<double> unix { get; set; }
        public Nullable<bool> procesado { get; set; }
    }
}
