//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BecDevGenEntradaSalidaCprEvent
{
    using System;
    using System.Collections.Generic;
    
    public partial class bec_event_salida_devolucion
    {
        public int id { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public string tipo_movimiento { get; set; }
        public Nullable<double> unix { get; set; }
        public string folio_definido { get; set; }
        public string codigo_producto { get; set; }
        public Nullable<double> cantidad_movimiento { get; set; }
        public string ruta_almacen { get; set; }
        public Nullable<int> id_agente { get; set; }
        public string serie_salida { get; set; }
        public Nullable<double> folio_salida { get; set; }
        public Nullable<int> id_documento_salida { get; set; }
        public Nullable<int> id_movimiento_salida { get; set; }
        public Nullable<bool> procesado_salida { get; set; }
        public string serie_entrada { get; set; }
        public Nullable<double> folio_entrada { get; set; }
        public Nullable<int> id_documento_entrada { get; set; }
        public Nullable<int> id_movimiento_entrada { get; set; }
        public Nullable<bool> procesado_entrada { get; set; }
    }
}
