//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BecDevGenEntradaSalidaCprEvent
{
    using System;
    using System.Collections.Generic;
    
    public partial class bec_event_cliente_documento
    {
        public int id { get; set; }
        public string codigo_cliente { get; set; }
        public string codigo_documento { get; set; }
        public string codigo_salida { get; set; }
        public string codigo_entrada { get; set; }
        public string codigo_factura { get; set; }
        public string codigo_pago { get; set; }
        public string codigo_almacen_defectuoso { get; set; }
        public string codigo_agente { get; set; }
    }
}
