//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BecDevGenEntradaSalidaCprEvent
{
    using System;
    using System.Collections.Generic;
    
    public partial class bec_event_documento_movimiento
    {
        public int id { get; set; }
        public Nullable<int> id_documento_encabezado { get; set; }
        public Nullable<int> id_movimiento_contpaq { get; set; }
        public string codigo_producto { get; set; }
        public Nullable<double> cantidad_producto { get; set; }
        public string tipo { get; set; }
        public Nullable<double> unix { get; set; }
        public Nullable<bool> procesado { get; set; }
    }
}
